"""Abstract agent adapter interface for all AI operations."""

from abc import ABC, abstractmethod
from collections.abc import AsyncIterator
from dataclasses import dataclass, field


@dataclass
class ClassificationResult:
    """Result of classifying a lecture artifact."""

    course_code: str
    week: int
    title: str
    confidence: float
    reasoning: str = ""


@dataclass
class SummaryResult:
    """Result of generating a lecture summary."""

    content_md: str
    embedded_images: list[str] = field(default_factory=list)


@dataclass
class FlashcardData:
    """A single flashcard generated by the AI."""

    front: str
    back: str
    tags: list[str] = field(default_factory=list)
    source_page_ref: int = 1


@dataclass
class QuizQuestionData:
    """A single quiz question generated by the AI."""

    question_type: str  # "multiple_choice" or "short_answer"
    question: str
    options: list[str] | None = None
    correct_answer: str = ""
    explanation: str = ""
    source_page_ref: int = 1


@dataclass
class AnswerResult:
    """Result of answering a question with citations."""

    answer: str
    citations: list[dict] = field(default_factory=list)


@dataclass
class ExtractionData:
    """Extraction content passed to AI operations."""

    pages: list[dict]
    metadata: dict


@dataclass
class CourseOpsAssessment:
    """An assessment extracted from a course document."""

    title: str
    assessment_type: str  # "exam", "assignment", "quiz", "project", "lab", "presentation", "other"
    weight_pct: float | None = None
    description: str = ""
    weeks_relevant: list[int] = field(default_factory=list)


@dataclass
class CourseOpsDeadline:
    """A deadline extracted from a course document."""

    title: str
    due_date: str  # ISO format date string "YYYY-MM-DD"
    deadline_type: str
    description: str = ""


@dataclass
class CourseOpsResult:
    """Result of extracting course logistics from a document."""

    assessments: list[CourseOpsAssessment] = field(default_factory=list)
    deadlines: list[CourseOpsDeadline] = field(default_factory=list)
    course_info: dict = field(default_factory=dict)
    confidence: float = 0.0


@dataclass
class ConceptData:
    """A single concept extracted by the AI."""

    name: str
    description: str
    category: str = "general"


@dataclass
class ConceptRelationData:
    """A relationship between two concepts."""

    source: str
    target: str
    relation_type: str = "related_to"
    confidence: float = 0.8


@dataclass
class ConceptExtractionResult:
    """Result of extracting concepts from lecture content."""

    concepts: list[ConceptData] = field(default_factory=list)
    relations: list[ConceptRelationData] = field(default_factory=list)


class AgentAdapter(ABC):
    """Abstract interface for AI operations.

    All AI calls go through this interface. v1 implements ClaudeCodeAdapter
    (subprocess to `claude -p`). Future adapters: AnthropicAPIAdapter,
    OllamaAdapter.
    """

    @abstractmethod
    async def classify_lecture(
        self, text_preview: str, filename: str, known_courses: list[str]
    ) -> ClassificationResult:
        """Identify course code, week number, and lecture title.

        Args:
            text_preview: Text from first 2 pages of the file.
            filename: Original filename.
            known_courses: List of existing course codes.

        Returns:
            ClassificationResult with course_code, week, title, confidence.
        """
        ...

    @abstractmethod
    async def generate_summary(
        self, extraction: ExtractionData, existing_summary: str | None
    ) -> SummaryResult:
        """Generate or update a lecture summary.

        Args:
            extraction: Extracted content from the lecture file.
            existing_summary: Previous summary markdown if updating.

        Returns:
            SummaryResult with markdown content and embedded image references.
        """
        ...

    @abstractmethod
    async def generate_flashcards(
        self, summary: str, extraction: ExtractionData, count: int
    ) -> list[FlashcardData]:
        """Generate flashcard Q&A pairs.

        Args:
            summary: Summary markdown for context.
            extraction: Full extraction data.
            count: Number of flashcards to generate.

        Returns:
            List of FlashcardData.
        """
        ...

    @abstractmethod
    async def generate_quiz(
        self, summary: str, extraction: ExtractionData, count: int
    ) -> list[QuizQuestionData]:
        """Generate quiz questions (MCQ + short answer).

        Args:
            summary: Summary markdown for context.
            extraction: Full extraction data.
            count: Number of questions to generate.

        Returns:
            List of QuizQuestionData.
        """
        ...

    @abstractmethod
    async def answer_question(self, question: str, context_chunks: list[dict]) -> AnswerResult:
        """Answer a question using retrieved context chunks.

        Args:
            question: The user's question.
            context_chunks: Relevant text chunks with metadata.

        Returns:
            AnswerResult with answer text and citations.
        """
        ...

    @abstractmethod
    async def extract_course_ops(
        self, document_text: str, course_code: str, document_type: str
    ) -> CourseOpsResult:
        """Extract assessments, deadlines, and course info from a course document.

        Args:
            document_text: Extracted text from the course document.
            course_code: Course code for context.
            document_type: Type of document (outline, rubric, handbook).

        Returns:
            CourseOpsResult with assessments, deadlines, and metadata.
        """
        ...

    @abstractmethod
    async def extract_concepts(
        self, text: str, existing_concepts: list[str] | None = None
    ) -> ConceptExtractionResult:
        """Extract concepts and relationships from lecture content.

        Args:
            text: Lecture text content.
            existing_concepts: Names of concepts already extracted for this course.

        Returns:
            ConceptExtractionResult with concepts and relations.
        """
        ...

    async def stream_answer(
        self, question: str, context_chunks: list[dict]
    ) -> AsyncIterator[str]:
        """Stream answer tokens for a question.

        Default implementation calls answer_question() and yields the full
        answer at once. Adapters with native streaming (Anthropic, OpenAI)
        override this to yield tokens incrementally.

        Args:
            question: The user's question.
            context_chunks: Relevant text chunks with metadata.

        Yields:
            Text token strings.
        """
        result = await self.answer_question(question, context_chunks)
        yield result.answer
