#!/usr/bin/env bash
# Forced command for the github-runner-deploy-studyaio key (authorized_keys).
# Rewritten 2026-09-27 when CI moved to GitLab.
#
# CANONICAL COPY: infra/deploy/deploy.sh in the StudyAIO repo. The live file is
# /opt/studyaio/deploy.sh on the deploy host and is deliberately UNTRACKED there
# -- `git checkout --force` during a deploy must not rewrite the script that is
# currently executing, because bash reads a script incrementally and would run
# the tail of the new file against the state of the old one. So this is applied
# by hand; see docs/deployment.md. Keep the two in step.
#
# The CI job supplies ONE argument -- the commit SHA that passed CI -- via
# SSH_ORIGINAL_COMMAND. Everything else happens here, which is what lets the key
# stay command-restricted: the deploy needs no scp and no arbitrary ssh, so a
# leaked key still cannot run anything but this script.
#
# Deliberately pulls images rather than building locally. The previous version
# ran `compose build`, and because the base compose declares build: for
# ui/api/worker/beat while the prod overlay sets image: ghcr.io/..., that built
# LOCAL images tagged with the GHCR names -- shadowing the very artifacts CI had
# tested. Pulling the exact tag keeps "what was tested" and "what runs" identical.
set -euo pipefail

cd /opt/studyaio

# Validate strictly. The forced command means this is the only entry point, so
# this pattern is the whole input surface -- anything not a hex SHA is refused.
REQ="${SSH_ORIGINAL_COMMAND:-}"
if ! [[ "$REQ" =~ ^[0-9a-f]{7,40}$ ]]; then
    echo "refusing: expected a commit SHA, got: '${REQ}'" >&2
    exit 64
fi
SHA="$REQ"
TAG="${SHA:0:7}"

COMPOSE="docker compose -f docker-compose.yml -f docker-compose.prod.yml"

# origin is GITLAB as of 2026-09-27 (gitlab-studyaio alias, read-only deploy key
# scoped to this project). The commit CI just built is therefore available
# immediately -- the deploy no longer waits on GitLab->GitHub mirror propagation,
# which is what it depended on when origin was git@github-studyaio:.
echo "==> Fetching ${SHA}..."
if ! git fetch --quiet origin; then
    echo "refusing: git fetch from origin failed" >&2
    exit 65
fi

# Distinguish "the mirror has not propagated" from "the checkout was blocked".
# The first version of this script piped checkout's stderr to /dev/null and
# reported EVERY failure as a missing commit, which sent the first real deploy
# chasing a mirror problem that did not exist -- the actual error was a dirty
# working tree.
if ! git cat-file -e "${SHA}^{commit}" 2>/dev/null; then
    echo "refusing: commit ${SHA} is not on origin (GitLab) -- was it actually pushed?" >&2
    exit 65
fi

# A deploy's contract is "run exactly this commit", so local edits to TRACKED
# files are drift and get discarded. Silently preserving them is how this tree
# ended up 77 commits stale with scp'd files sitting on top of it. Untracked
# files (backups/, patches, this script) are NOT touched by checkout --force.
DRIFT="$(git status --porcelain --untracked-files=no || true)"
if [ -n "$DRIFT" ]; then
    echo "==> Discarding local modifications to tracked files:"
    echo "${DRIFT}" | sed 's/^/      /'
fi
git checkout --force --quiet --detach "${SHA}"
echo "==> Checked out $(git rev-parse --short=12 HEAD)"

echo "==> Pinning images to ${TAG}..."
# Re-pinned on every deploy on purpose: this .env is regenerated by the secrets
# export, which drops GHCR_OWNER/IMAGE_TAG and silently leaves compose resolving
# ${IMAGE_TAG:-latest}. Writing it immediately before `up` is what keeps the
# running stack on the tested tag.
touch .env
sed -i '/^GHCR_OWNER=/d;/^IMAGE_TAG=/d' .env
printf 'GHCR_OWNER=%s\nIMAGE_TAG=%s\n' "alcybersec" "${TAG}" >> .env

# Checked BEFORE pulling. Pipeline 368 died halfway through extracting the torch
# layer with "no space left on device" -- which surfaces as a containerd error
# naming a blob digest and reads like a registry fault, not a full disk. The
# host had 575M free. Failing here instead costs a second and says what is
# actually wrong.
#
# 8G is the working figure: the api image carries torch, LibreOffice and the
# baked embedding model, and a pull needs room for the compressed layer AND its
# extracted form at once.
echo "==> Checking disk space..."
REQUIRED_GB=8
DOCKER_ROOT="$(docker info --format '{{.DockerRootDir}}' 2>/dev/null || echo /var/lib/docker)"
AVAIL_GB="$(( $(df -P -k "${DOCKER_ROOT}" | awk 'NR==2{print $4}') / 1024 / 1024 ))"
if [ "${AVAIL_GB}" -lt "${REQUIRED_GB}" ]; then
    echo "refusing: need ~${REQUIRED_GB}G free on ${DOCKER_ROOT} to pull and extract, have ${AVAIL_GB}G" >&2
    echo "  reclaim with:" >&2
    echo "    docker image prune -af --filter 'until=168h'" >&2
    echo "    docker builder prune -af" >&2
    exit 66
fi
echo "    ${AVAIL_GB}G available on ${DOCKER_ROOT}"

echo "==> Pulling images..."
$COMPOSE pull --quiet

echo "==> Starting containers..."
$COMPOSE up -d --no-build --remove-orphans

echo "==> Running migrations..."
$COMPOSE exec -T api alembic upgrade head

echo "==> Verifying health..."
sleep 5
$COMPOSE exec -T api python -c "import urllib.request; urllib.request.urlopen('http://localhost:8000/health/ready')"
curl -fsS -o /dev/null "http://localhost:${UI_PORT:-3001}/"

# -a, NOT a bare -f. Without -a this removes only DANGLING images, so every
# deploy since this script was written left its predecessor's tagged image on
# disk permanently: 33 images totalling 24G by 2026-09-28, 6.5G of it unused.
# That is how the host reached 99% and failed the deploy above -- the cleanup
# step existed the whole time and was reclaiming next to nothing.
#
# The until filter keeps roughly a week of recent tags as local rollback
# targets; anything older is re-pullable from GHCR. Images belonging to a
# RUNNING container are never removed by prune, so the live stack is safe.
echo "==> Pruning old images..."
docker image prune -af --filter "until=168h" >/dev/null
docker builder prune -af >/dev/null 2>&1 || true

echo "==> Deploy complete: ${SHA} (tag ${TAG})"
