#!/usr/bin/env bash
# StudyAIO — Self-Hosted Setup Script
# Interactive setup for deploying StudyAIO with Docker Compose + Traefik TLS.
#
# Usage: bash scripts/setup-selfhosted.sh

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

info()  { echo -e "${BLUE}[INFO]${NC} $*"; }
ok()    { echo -e "${GREEN}[OK]${NC} $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
err()   { echo -e "${RED}[ERROR]${NC} $*" >&2; }

# ── Prerequisite checks ────────────────────────────────────────────

check_prereqs() {
    info "Checking prerequisites..."

    if ! command -v docker &>/dev/null; then
        err "Docker is not installed. See https://docs.docker.com/engine/install/"
        exit 1
    fi
    ok "Docker found: $(docker --version)"

    if ! docker compose version &>/dev/null; then
        err "Docker Compose v2 is required. See https://docs.docker.com/compose/install/"
        exit 1
    fi
    ok "Docker Compose found: $(docker compose version --short)"

    if ! docker info &>/dev/null 2>&1; then
        err "Docker daemon is not running or you lack permissions. Try: sudo usermod -aG docker \$USER"
        exit 1
    fi
    ok "Docker daemon is running"
}

# ── Interactive prompts ────────────────────────────────────────────

prompt_config() {
    echo ""
    echo -e "${GREEN}══════════════════════════════════════════${NC}"
    echo -e "${GREEN}  StudyAIO Self-Hosted Setup${NC}"
    echo -e "${GREEN}══════════════════════════════════════════${NC}"
    echo ""

    read -rp "Domain name (e.g. studyaio.example.com): " DOMAIN
    if [[ -z "$DOMAIN" ]]; then
        err "Domain is required for TLS certificate generation."
        exit 1
    fi

    read -rp "Email for Let's Encrypt notifications: " ACME_EMAIL
    if [[ -z "$ACME_EMAIL" ]]; then
        err "Email is required for Let's Encrypt."
        exit 1
    fi

    read -rp "Postgres password [studyaio]: " PG_PASS
    PG_PASS="${PG_PASS:-studyaio}"

    JWT_SECRET=$(openssl rand -hex 32 2>/dev/null || python3 -c "import secrets; print(secrets.token_hex(32))")

    read -rp "Enable Prometheus metrics? (y/N): " PROM_ENABLED
    PROM_ENABLED=$([[ "$PROM_ENABLED" =~ ^[Yy] ]] && echo "true" || echo "false")

    echo ""
    info "Configuration summary:"
    echo "  Domain:     $DOMAIN"
    echo "  Email:      $ACME_EMAIL"
    echo "  Postgres:   studyaio / ******"
    echo "  JWT Secret: (auto-generated)"
    echo "  Prometheus: $PROM_ENABLED"
    echo ""
    read -rp "Proceed? (Y/n): " CONFIRM
    if [[ "$CONFIRM" =~ ^[Nn] ]]; then
        info "Aborted."
        exit 0
    fi
}

# ── Generate .env ──────────────────────────────────────────────────

generate_env() {
    if [[ -f .env ]]; then
        warn ".env already exists — backing up to .env.backup"
        cp .env .env.backup
    fi

    cat > .env <<ENVEOF
# Generated by setup-selfhosted.sh on $(date -Iseconds)

# === Domain & TLS ===
DOMAIN=${DOMAIN}
ACME_EMAIL=${ACME_EMAIL}

# === Database ===
DATABASE_URL=postgresql+asyncpg://studyaio:${PG_PASS}@db:5432/studyaio
DATABASE_URL_SYNC=postgresql://studyaio:${PG_PASS}@db:5432/studyaio
POSTGRES_USER=studyaio
POSTGRES_PASSWORD=${PG_PASS}
POSTGRES_DB=studyaio

# === Redis ===
REDIS_URL=redis://redis:6379/0

# === App ===
DATA_DIR=/app/data
LOG_LEVEL=INFO
SELF_HOSTED=true
CORS_ORIGINS=https://${DOMAIN}

# === Auth ===
JWT_SECRET_KEY=${JWT_SECRET}
JWT_ALGORITHM=HS256

# === Observability ===
PROMETHEUS_ENABLED=${PROM_ENABLED}
ENVEOF

    ok ".env generated"
}

# ── Create directories ─────────────────────────────────────────────

create_dirs() {
    info "Creating directories..."
    mkdir -p data/uploads data/extractions data/summaries data/courseops backups
    ok "Data directories created"
}

# ── Build & start ──────────────────────────────────────────────────

start_stack() {
    info "Building images (this may take a few minutes)..."
    docker compose -f docker-compose.yml -f docker-compose.selfhosted.yml build

    info "Starting services..."
    docker compose -f docker-compose.yml -f docker-compose.selfhosted.yml up -d

    info "Waiting for database to be ready..."
    for i in $(seq 1 30); do
        if docker compose exec -T db pg_isready -U studyaio &>/dev/null; then
            ok "Database is ready"
            break
        fi
        sleep 2
    done

    info "Running database migrations..."
    docker compose exec -T api alembic upgrade head
    ok "Migrations complete"
}

# ── Seed data ──────────────────────────────────────────────────────

seed_data() {
    read -rp "Seed achievement definitions? (Y/n): " SEED_ACH
    if [[ ! "$SEED_ACH" =~ ^[Nn] ]]; then
        info "Seeding achievements..."
        docker compose exec -T api python -m scripts.seed_achievements 2>/dev/null || \
            docker compose exec -T api python scripts/seed_achievements.py 2>/dev/null || \
            warn "Achievement seeding skipped (script not found)"
    fi
}

# ── Final status ───────────────────────────────────────────────────

show_status() {
    echo ""
    echo -e "${GREEN}══════════════════════════════════════════${NC}"
    echo -e "${GREEN}  StudyAIO is running!${NC}"
    echo -e "${GREEN}══════════════════════════════════════════${NC}"
    echo ""
    echo "  URL:          https://${DOMAIN}"
    echo "  API Docs:     https://${DOMAIN}/docs"
    echo "  Health Check: https://${DOMAIN}/health"
    echo ""
    echo "  Useful commands:"
    echo "    docker compose -f docker-compose.yml -f docker-compose.selfhosted.yml logs -f"
    echo "    docker compose -f docker-compose.yml -f docker-compose.selfhosted.yml down"
    echo "    make backup"
    echo ""
    echo "  TLS certificate will be provisioned automatically by Let's Encrypt."
    echo "  Make sure ports 80 and 443 are open and DNS points to this server."
    echo ""
}

# ── Main ───────────────────────────────────────────────────────────

main() {
    check_prereqs
    prompt_config
    generate_env
    create_dirs
    start_stack
    seed_data
    show_status
}

main "$@"
